# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Replicateme < Formula
  desc "CLI that learns your writing style and generates messages that sound like you"
  homepage "https://replicateme.cc"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jschell12/replicateme/releases/download/v0.2.0/replicateme_darwin_amd64.tar.gz"
      sha256 "e4e8d69cc36e7431f20e393320306bc3014e1943d84cc06cb078076620e4f5a5"

      define_method(:install) do
        bin.install "replicateme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jschell12/replicateme/releases/download/v0.2.0/replicateme_darwin_arm64.tar.gz"
      sha256 "801e9dfd9b2ecc453e834bf37f75aa459e2f7c00dc872f851932baef70826066"

      define_method(:install) do
        bin.install "replicateme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jschell12/replicateme/releases/download/v0.2.0/replicateme_linux_amd64.tar.gz"
      sha256 "f71d5455284258bb07402137e697a385e94be7389267062c1cb896a36450fece"
      define_method(:install) do
        bin.install "replicateme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jschell12/replicateme/releases/download/v0.2.0/replicateme_linux_arm64.tar.gz"
      sha256 "2a454a147a4e51a6e80a448bb98283872b070a74cb773462155c1345cf6d37ba"
      define_method(:install) do
        bin.install "replicateme"
      end
    end
  end
end
