# This file was generated by GoReleaser. DO NOT EDIT.
cask "replicateme" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "5082bb01353c206ea368324eb110ea14ba147059910e67720db2f5817698f947"
      url "https://github.com/jschell12/replicateme/releases/download/v#{version}/replicateme_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "40bede374fd0ad886171980cab5177480fb46786e8c997ab8fe72bb9722bd108"
      url "https://github.com/jschell12/replicateme/releases/download/v#{version}/replicateme_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2a7fc9ba690d263c0caad5310dfb681f4b9859c8643569892b5711458c118a83"
      url "https://github.com/jschell12/replicateme/releases/download/v#{version}/replicateme_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8a6d7524d0f53bf73e78e3d2b238e09f931877eeb8035b7b81fd005705d2c8f4"
      url "https://github.com/jschell12/replicateme/releases/download/v#{version}/replicateme_linux_amd64.tar.gz"
    end
  end

  name "replicateme"
  desc "CLI that learns your writing style and generates messages that sound like you"
  homepage "https://replicateme.cc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "replicateme"

  # No zap stanza required
end
