# This file was generated by GoReleaser. DO NOT EDIT.
cask "replicateme" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "d4600cb283d57ef1bcf5b122cd5e98f800414910e8e2eabd1626fcc708b1310b"
      url "https://github.com/jschell12/replicateme/releases/download/v#{version}/replicateme_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "838a2e04960d157ce7186ad253873ff954cdf80cbf407407654798f65207ad32"
      url "https://github.com/jschell12/replicateme/releases/download/v#{version}/replicateme_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1a25dfa541e8cf71b4a82cb0eaad8fdbece389b334f65bb9656130a51bc6d064"
      url "https://github.com/jschell12/replicateme/releases/download/v#{version}/replicateme_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d6d158b203d160c684e3a205ca95ab37b53a65ee90fe6739820ff37b53bc82e"
      url "https://github.com/jschell12/replicateme/releases/download/v#{version}/replicateme_linux_amd64.tar.gz"
    end
  end

  name "replicateme"
  desc "CLI that learns your writing style and generates messages that sound like you"
  homepage "https://replicateme.cc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "replicateme"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/replicateme"]
  end

  # No zap stanza required
end
