# This file was generated by GoReleaser. DO NOT EDIT.
cask "workforce" do
  binary "workforce", target: "wf"

  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "57214b64333868f50169342230b94e154652536b186f28133f87d09259f24aff"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "53edd9806b8e7027b5b3adfded164ac54dc09f276da19ed64a3c65c6e56ac971"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1b5114025d3a8804a8d7c89134efbc0b797e969b6a5f7812137228f2888a2146"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1c4bed108f3c61ae4c04757fa81b6ac90418cbb3fc8615853e77896c19a2eff8"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_linux_amd64.tar.gz"
    end
  end

  name "workforce"
  desc "Starts and accounts for the Claude Code sessions running on a machine"
  homepage "https://github.com/jschell12/workforce"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "workforce"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/workforce"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    wf needs a config before it can do anything:

      mkdir -p ~/.claude/workforce
      curl -fsSL -o ~/.claude/workforce/roles.toml https://raw.githubusercontent.com/jschell12/workforce/main/config/roles.example.toml

    Permission profiles go in ~/.claude/workforce/perm/. Run `wf doctor` once
    you have edited the config: it checks every persona, permission profile
    and credential key the config names.
  EOS
end
