# This file was generated by GoReleaser. DO NOT EDIT.
cask "workforce" do
  binary "workforce", target: "wf"

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "e93c2d6fb8fe39ab327d69502ce6043a73fc2446da64d04d8224556cb1581295"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2791da4f948423f71fd1c56ec16b28607b97a77f0b9e8e11d2a3a2b0ba8f04bb"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3fd47fb2152b8aa5ab61fcb99028df60b283c7b54e99143ae673fc670b974f4d"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "964c7e33152e7ebdffc63a352aa0854bd3191c7c28f156f8bd40d0ffec59830c"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_linux_amd64.tar.gz"
    end
  end

  name "workforce"
  desc "Starts and accounts for the Claude Code sessions running on a machine"
  homepage "https://github.com/jschell12/workforce"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "workforce"

  # No zap stanza required

  caveats <<~EOS
    wf needs a config before it can do anything:

      mkdir -p ~/.claude/workforce
      curl -fsSL -o ~/.claude/workforce/roles.toml https://raw.githubusercontent.com/jschell12/workforce/main/config/roles.example.toml

    Permission profiles go in ~/.claude/workforce/perm/. Run `wf doctor` once
    you have edited the config: it checks every persona, permission profile
    and credential key the config names.
  EOS
end
