# This file was generated by GoReleaser. DO NOT EDIT.
cask "workforce" do
  binary "workforce", target: "wf"

  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "0eeb2f16158bb5895ef7ff3c7fc209414099c4d17e91d58d64e259ae0c2d34f5"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ddb773a6d67f468ebb8967bc8362b773f1655ee0df0c6b6a2afada5f2596c14e"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a50eaafc15c86472014bab80978f4933f22f6310afd0935b135998c373b279c2"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1a97a4a8d5be66cab7d214628b49080cf8d148b76c7dbf2b3808520fdd0f843"
      url "https://github.com/jschell12/workforce/releases/download/v#{version}/workforce_linux_amd64.tar.gz"
    end
  end

  name "workforce"
  desc "Starts and accounts for the Claude Code sessions running on a machine"
  homepage "https://github.com/jschell12/workforce"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "workforce"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/workforce"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    wf needs a config before it can do anything:

      mkdir -p ~/.claude/workforce
      curl -fsSL -o ~/.claude/workforce/roles.toml https://raw.githubusercontent.com/jschell12/workforce/main/config/roles.example.toml

    Permission profiles go in ~/.claude/workforce/perm/. Run `wf doctor` once
    you have edited the config: it checks every persona, permission profile
    and credential key the config names.
  EOS
end
